mmk8ds/mmk8ds/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('statsviewers.urls')),
    path('admin/', admin.site.urls),
]

mmk8ds/statsviewers/urls.py
from django.urls import path
from . import views

app_name = "statsviewers"

urlpatterns = [
    path('', views.index, name='index'),
    path('tracks/', views.tracks, name='tracks'),
    path('builds/', views.builds, name='builds'),
]

mmk8ds/statsviewers/models.py
from datetime import datetime
from django.db import models
from django.utils import timezone
from datetime import date

class Driver(models.Model):
    icon = models.ImageField(null=True, blank=True, upload_to='statsviewers\static\statsviewers\media\img\drivers')
    en_name = models.CharField(max_length=64, blank=True, null=True)
    fr_name = models.CharField(max_length=64, blank=True, null=True)

    def __str__(self) -> str:
        return f"{self.en_name} ({self.fr_name})"

class Body(models.Model):
    icon = models.ImageField(null=True, blank=True, upload_to='statsviewers\static\statsviewers\media\img\drivers')
    en_name = models.CharField(max_length=64, blank=True, null=True)
    fr_name = models.CharField(max_length=64, blank=True, null=True)

    def __str__(self) -> str:
        return f"{self.en_name} ({self.fr_name})"

class Tire(models.Model):
    icon = models.ImageField(null=True, blank=True, upload_to='statsviewers\static\statsviewers\media\img\drivers')
    en_name = models.CharField(max_length=64, blank=True, null=True)
    fr_name = models.CharField(max_length=64, blank=True, null=True)

    def __str__(self) -> str:
        return f"{self.en_name} ({self.fr_name})"

class Glider(models.Model):
    icon = models.ImageField(null=True, blank=True, upload_to='statsviewers\static\statsviewers\media\img\drivers')
    en_name = models.CharField(max_length=64, blank=True, null=True)
    fr_name = models.CharField(max_length=64, blank=True, null=True)

    def __str__(self) -> str:
        return f"{self.en_name} ({self.fr_name})"


class Build(models.Model):
    name = models.CharField(max_length=64)
    driver = models.ManyToManyField(Driver, blank=True, null=True)
    body = models.ManyToManyField(Body, blank=True, null=True)
    tire = models.ManyToManyField(Tire, blank=True, null=True)
    glider = models.ManyToManyField(Glider, blank=True, null=True)

    def __str__(self) -> str:
        return f"{self.name}"

    def getDriver(self):
        return str(self.driver)

class Gametype(models.Model):
    name = models.CharField(max_length=64)

    def __str__(self) -> str:
        return f"{self.name}"

class Cup(models.Model):
    icon = models.ImageField(null=True, blank=True, upload_to='statsviewers\static\statsviewers\media\img\cup')
    en_name = models.CharField(max_length=64, blank=True, null=True)
    fr_name = models.CharField(max_length=64, blank=True, null=True)

    def __str__(self) -> str:
        return f"{self.en_name} ({self.fr_name})"

    def tracklist(self) -> list:
        return self.track_set.all()

    def imgLink(self) -> str:
        return str(self.icon)[20:]

class Track(models.Model):
    en_name = models.CharField(max_length=64, blank=True, null=True)
    fr_name = models.CharField(max_length=64, blank=True, null=True)
    icon = models.ImageField(null=True, blank=True, upload_to='statsviewers\static\statsviewers\media\img\circuit')
    cup = models.ManyToManyField(Cup, blank=True, null=True)

    def __str__(self) -> str:
        return f"{self.en_name} ({self.fr_name})"
    def imgLink(self) -> str:
        return str(self.icon)[20:]


class Courses(models.Model):
    resultat = models.IntegerField(default=1, blank=True, null=True)
    deco = models.BooleanField(default=False, blank=True, null=True)
    number_of_bots = models.IntegerField(default=0, blank=True, null=True)
    circuit = models.ManyToManyField(Track, blank=True, null=True)
    build = models.ManyToManyField(Build, blank=True, null=True)
    gametype = models.ManyToManyField(Gametype, blank=True, null=True)
    date_course = models.DateField(null=True, blank=True)

    def __str__(self) -> str:
        return f"{self.date_course} - {self.resultat}th"

mmk8ds/statsviewers/views.py
from django.http import Http404, HttpResponse
from .models import *
from django.template import loader


def index(request):
    template = loader.get_template('statsviewers/index.html')
    data = {}
    return HttpResponse(template.render(data, request))


def tracks(request):
    template = loader.get_template('statsviewers/tracklist.html')
    alltracks = Cup.objects.all()
    data = {'itemList':alltracks}
    return HttpResponse(template.render(data, request))

def builds(request):
    template = loader.get_template('statsviewers/buildlist.html')
    allbuilds = Build.objects.all()
    print('DEBUG')
    print('DEBUG')
    print('DEBUG')
    print(allbuilds)
    data = {'itemList':allbuilds}
    return HttpResponse(template.render(data, request))

mmk8ds/statsviewers/templates/statsviewers/base_page.html
<!DOCTYPE html>
{% load static %}
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'statsviewers/css/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">   
    <title>{% block titre %}{% endblock %}</title>
</head>
<body>
    <center>
    <nav>
        <a href="{% url 'statsviewers:index'%}"><button class="navbtn">accueil</button></a>
        <a href="{% url 'statsviewers:tracks'%}"><button class="navbtn">Tracks</button></a>
        <a href="{% url 'statsviewers:builds'%}"><button class="navbtn">Builds</button></a>
    </nav><br>
    </center>
    {% block content %}
    {% endblock %}
</body>
</html>

mmk8ds/statsviewers/templates/statsviewers/buildlist.html
{% extends "statsviewers/base_page.html" %}
{% load static %}
{% block titre %}Builds{% endblock %}
{% block content %}
    {% for element in itemList %}
    <div class="container">
        <div class="row">
            <div class="col-2">                                
            </div>
            <div class="col-8">
                <div class="itemCard">
                    <h2>{{ element }}</h2>
                    <hr class="solid">
                    <div class="container">
                        <div class="row">
                            <div class="col-6">
                                <h5>{% for item in element.driver.all %}{{item}}{%endfor%}</h5>                                  
                            </div>
                            <div class="col-6">
                                <h5>{% for item in element.body.all %}{{item}}{%endfor%}</h5>
                            </div>
                            <div class="col-6">    
                                <h5>{% for item in element.tire.all %}{{item}}{%endfor%}</h5>
                            </div>
                            <div class="col-6">
                                <h5>{% for item in element.glider.all %}{{item}}{%endfor%}</h5>
                            </div>
                        </div>
                    </div>
                    
                </div>                               
            </div>
            <div class="col-2">                                
            </div>
        </div>
    </div>
    {% endfor %}
{% endblock %}

mmk8ds/statsviewers/templates/statsviewers/index.html
{% extends "statsviewers/base_page.html" %}
{% load static %}
{% block titre %}Index{% endblock %}

{% block content %}


<p>{% lorem 7 p random %}
</p>


{% endblock %}

mmk8ds/statsviewers/templates/statsviewers/tracklist.html
{% extends "statsviewers/base_page.html" %}
{% load static %}
{% block titre %}Tracks{% endblock %}
{% block content %}
    {% for element in itemList %}
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="itemCard">
                    <img src="{% static element.imgLink %}" class="cuppic">
                    <h2 class="cuptitle">{{ element }}</h2>
                    <hr class="solid">
                    <div class="container">
                        <div class="row">
                            {% for item in element.tracklist %}
                            <div class="col-3">
                                <h5 class="tracktitle">{{item}}</h5>
                                <img src="{% static item.imgLink %}" class="trackpic">                            
                            </div>
                            {%endfor%}
                        </div>
                    </div>
                    
                </div>                               
            </div>
        </div>
    </div>
    <br><br>
    {% endfor %}
{% endblock %}